### ISSUE TITLE
crictl logs should share code from kubelet.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-tools#169]
Currently, we copy all the code from kubelet.

We should make the code in kubelet to be a CRI log parsing library. And import the library in `crictl`.

**Comment by yanxuean** [comment]
Do you mean cri-tools/cmd/crictl/logs.go?

**Comment by Random-Liu** [comment]
Yeah, most of the code there is the same with https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_logs.go

**Comment by yanxuean** [comment]
I will fix it late.

**Comment by yanxuean** [comment]
@Random-Liu   help:)
The cri-tools depend on k8s.io/kubernetes/pkg/kubelet/kuberuntime.
The kuberuntime depend on these as below:
```
k8s.io/apiextensions-apiserver
k8s.io/apiserver
k8s.io/metrics
```
The problem is how do I get the version of k8s.io/apiextensions-apiserver corresponding to k8s.io/kubernetes?

I checked kubernetes/Godeps/Godeps.json, there is not answer.

**Comment by yanxuean** [comment]
/cc @Random-Liu    
The problem is how do I get the version of k8s.io/apiextensions-apiserver corresponding to k8s.io/kubernetes?

**Comment by feiskyer** [comment]
@yanxuean @Random-Liu We need to make kubelet logs a lib first. Let's make the code in kubelet to be a CRI log parsing library.

**Comment by yanxuean** [comment]
Agree.  Now we need import kuberuntime. It is too complex.

**Comment by yanxuean** [comment]
The logs is indepent function.
