### ISSUE TITLE
some questions about cri-tools

### ISSUE THREAD

**Issue by lcfang** [kubernetes-incubator/cri-tools#224]
critest is composed of two components: validation and performance benchmark test suites.
In doc [Container Runtime Interface (CRI) Validation Testing](https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/validation.md), it says 

> CRI validation testing provides a test framework and a suite of tests to validate that the Container Runtime Interface (CRI) server implementation meets all the requirements. This allows the CRI runtime developers to verify that their runtime conforms to CRI, without needing to set up Kubernetes components or run Kubernetes end-to-end tests.

In doc [Container Runtime Interface (CRI) Performance Benchmarking](https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/benchmark.md), it also says

> CRI performance benchmarking provides a benchmarking framework for CRI-compatible container runtimes. This allows the CRI runtime developers to benchmark the performance of their runtime without needing to set up Kubernetes components or run Kubernetes benchmark tests.

If I am a  CRI runtime developers, I wonder which test I should run to confirm my product will go well for kubernetes. Is just the validation test, or just the performance benchmark test, or both of them? Or what some other test I should do?

**Comment by lcfang** [comment]
cc @yujuhong   @dchen1107

**Comment by lcfang** [comment]
Hi @Random-Liu  @euank @feiskyer @heartlock @mrunalp @xlgao-zju @runcom 
I am looking forward of your replying. Thanks.

**Comment by feiskyer** [comment]
> If I am a CRI runtime developers, I wonder which test I should run to confirm my product will go well for kubernetes. Is just the validation test, or just the performance benchmark test, or both of them

Validation tests, especially conformance tests. 

Benchmarking tests could help to benchmark the runtime performance, but there is no standard what performance should runtime reach.

**Comment by lcfang** [comment]
@feiskyer ,Thanks for your reply.
So , If my product accomplish the validation test, is it means it can be used for the kubernetes?

**Comment by Random-Liu** [comment]
> So , If my product accomplish the validation test, is it means it can be used for the kubernetes?

That is the eventual goal. However, that is still not the case today. Passing CRI validation test will be the first step for your container runtime. After that, you still need to run all Kubernetes e2e test with your container runtime to make sure it is feature complete for Kubernetes.

**Comment by lcfang** [comment]
Oh, I think I have get it. Thank you.

**Comment by lcfang** [comment]
Hi @Random-Liu , 
As you say, 

> That is the eventual goal

- I wonder if  the cri-tools's eventual goal is be the standard of kubernetes community to verify some cri can be used for kubernetes. 

- And if so, we desire to reslize the goal with the cri-tools team as soon as possible as we have some product suit this.

- And the last, we want to know the time or the release when it can be the standard, and what the team's plan is. And so far, what's the incompletion of this tool?

Forgiving my verbosity. Looking forward to your reply. Thank you.
@dchen1107 @euank @feiskyer @heartlock @mrunalp @xlgao-zju @runcom

**Comment by lcfang** [comment]
sig/node

**Comment by lichuqiang** [comment]
+1 for what @lcfang said.
We always have a need of verifying if a runtime provided could satisfy the requirement of k8s in our daily development, seems still we could not ensure its usability even if it passes all the existing validation and e2e tests. Thus, very eager to see an official standard to manage the validation.
Also, I found task `graduate crictl to beta` listed in 2018 Sig-node plan, not sure if the `critest` part is included though. 
Would like to know your plans, and help make contributions if possible. Expect to see the thing mature ASAP
Thanks a lot:)

**Comment by feiskyer** [comment]
Thanks for raising the question.

> I wonder if the cri-tools's eventual goal is be the standard of kubernetes community to verify some cri can be used for kubernetes.

This is true.

> And the last, we want to know the time or the release when it can be the standard, and what the team's plan is. And so far, what's the incompletion of this tool?

We need to stabilize CRI itself before this, while CRI is still under quick evolving (e.g. sig-node is still working on logging, authenticating, versioning and so on).

> Also, I found task graduate crictl to beta listed in 2018 Sig-node plan, not sure if the critest part is included though.

critest is included.

Also please note that critest is only validating with kubelet localhost. Passing it doesn't ensure the cluster network is working properly. That's why kubernetes e2e test is also required. 

> Would like to know your plans, and help make contributions if possible. Expect to see the thing mature ASAP

crictl and critest will evolve together with CRI updates.

@lcfang @lichuqiang we're welcomed of any kinds contributions. If you find something are missing, please do not hesitate to raise it up, or send PRs.

**Comment by lichuqiang** [comment]
@feiskyer Thanks for your reply!
> Also please note that critest is only validating with kubelet localhost. Passing it doesn't ensure the cluster network is working properly. That's why kubernetes e2e test is also required.

In fact our use case is: we have a brother department that help maintain the docker, and would provide it of new version regularly, so what we concerned about most is if the runtime itself could satisfy the requirement of k8s(mainly CRI). So things like cluster network may not within the scope of concern?

Please correct me if any mis-understanding :)

**Comment by feiskyer** [comment]
> So things like cluster network may not within the scope of concern?

Just FYI. Some runtime upgrades may break networking, e.g. docker v1.12 to v1.13 disables forward.

**Comment by yujuhong** [comment]
We (sig-node) are aware of the issue, and am in the process of coming up with a testing process for CRI runtimes. The details are TBD, but stay tuned.

Both @Random-Liu and @feiskyer have provided solid suggestions.
 - Use the CRI validation suites (critest) for your development. 
 - Keep a regular k8s node e2e suite because 1) it has higher test coverage, and 2) it tests specific use pattern by kubelet (for reliability)
 - For significant changes (e.g., upgrading runtime versions), run a k8s cluster e2e suite to test networking changes.

For your specific problem (upgrading docker), fixing the API version kubelet uses to talk to docker would help avoid unnecessary surprises (see https://github.com/kubernetes/kubernetes/issues/53221). AFAIK, no one is working on that though.
